### ISSUE TITLE
Signed in as "user@example.com"

### ISSUE THREAD

**Issue by stefwalter** [redhat-developer/podman-desktop-redhat-account-ext#59]
When signed into the Podman Desktop "Authentication" "Red Hat SSO" extension, I see "user.example.com" as my user name:

![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/795070/04264b20-9974-4fd0-8321-9dff9eed55b1)

I would expect it to say: "swalter@redhat.com"

I logged in via Red Hat SSO.

```
$ podman images | grep account-ext
quay.io/redhat-developer/podman-desktop-redhat-account-ext      0.0.2-alpha.2      c7bd1362e9ba  13 days ago   2.12 MB
```

```
$ flatpak list | grep Podman
Podman Desktop                 io.podman_desktop.PodmanDesktop               1.7.1             stable               system
```

**Comment by vrothberg** [comment]
Thanks for filing!  I cannot reproduce with the latest main branches of Podman Desktop and this extension.

**Comment by dgolovin** [comment]
There is something unique about this account. The accessToken generated is supposed to have preferred_username claim for all the users, because 'id.username' scope is used when talking to SSO host.

I added another scope 'email', which should add 'email' claim to the token. This claim is used as alternative if 'preferred_username' is not present.

I wonder what is shown on https://console.redhat.com in place of red square (see below)

![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/620330/ee2593c4-25ad-41cb-9913-c01a3c785247)

**Comment by dgolovin** [comment]
The CI build with change above is available from `ghcr.io/redhat-developer/podman-desktop-redhat-account-ext:latest`. 
@stefwalter could you give it a try? If it does not help, I'll ask subscription team what we could do for users without preferred_username and email claims.

**Comment by benoitf** [comment]
@dgolovin also in case of missing name, should we display `N/A` or `email not found` rather than `user@example.com` as I think it's confusing to see this email address

**Comment by slemeur** [comment]
+1 with @benoitf
